apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx1
  labels:
    app: nginx1
    company: devseccops
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: external-app
      app.kubernetes.io/instance: nginx1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: external-app
        app.kubernetes.io/instance: nginx1
    spec:
      serviceAccountName: stage-nginx1-sa
      securityContext: {}
      containers:
        - name: nginx1
          securityContext: {}
          image: nginx:latest
          imagePullPolicy: 'Always'
          env:
            - name: "ENVIRONMENT"
              value: stage
          resources:
            requests:
              memory: '256Mi'
              cpu: '200m'
            limits:
              memory: '256Mi'
              cpu: '200m'
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
