apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: {{ .Values.namespace.name }}
  labels:
    app: nginx
    company: devseccops
  annotations:
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
    argocd.argoproj.io/sync-wave: "4"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: external-app
      app.kubernetes.io/instance: nginx
  template:
    metadata:
      labels:
        app.kubernetes.io/name: external-app
        app.kubernetes.io/instance: nginx
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      securityContext: {}
      containers:
        - name: nginx
          securityContext: {}
          image: nginx:latest
          imagePullPolicy: 'Always'
          env:
            - name: "ENVIRONMENT"
              value: stage
          resources:
            requests:
              memory: '256Mi'
              cpu: '200m'
            limits:
              memory: '256Mi'
              cpu: '200m'
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10

